title: Welcome to my blog!
description: > # this means to ignore newlines until "baseurl:"
  Chào mừng đến với blog của tôi! Chúc các bạn một ngày vui vẻ.
  Tôi là Tào Tháo. Coder never die
permalink: '/blog/:title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tào Tháo # add your name
author-img: avatar.jpg # add your photo
about-author: I am a web developer focusing on back-end development. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: tranvandiep010 # add your Facebook handle
social-github: tranvandiep010 # add your Github handle
social-linkedin: phoenix010 # add your Linkedin handle
social-email: trandiep10121999@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-167985535-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-cayman
baseurl: /
profileurl: /profile
